version: '3.7'

services:
    web:
        build: ./web
        command: python manage.py run -h 0.0.0.0
        volumes:
            - ./web/:/usr/src/web/
        ports:
            - 5000:5000
        env_file:
            - ./.env
    db:
        image: postgres:13-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            ./.env.db

volumes:
    postgres_data: